#!/usr/bin/env python3
"""Report simple code-health metrics for Ferrython.

The goal is not to enforce style. It gives reviewers an objective baseline for
large-file and large-dispatch refactors.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re
from typing import Iterable


DEFAULT_ROOTS = ("crates", "stdlib", "tests", "tools")
DEFAULT_GLOBS = ("*.rs", "*.py")
ITEM_RE = re.compile(
    r"^\s*(?:pub(?:\([^)]*\))?\s+)?(?:async\s+)?(?:fn|struct|enum|trait|impl)\b"
)


@dataclass(frozen=True)
class FileStats:
    path: Path
    lines: int
    matches: int
    items: int
    extension: str

    @property
    def match_density(self) -> float:
        if self.lines == 0:
            return 0.0
        return self.matches * 1000.0 / self.lines


def iter_source_files(repo: Path, roots: Iterable[str], globs: Iterable[str]) -> Iterable[Path]:
    for root_name in roots:
        root = repo / root_name
        if not root.exists():
            continue
        for glob in globs:
            yield from root.rglob(glob)


def file_stats(repo: Path, path: Path) -> FileStats:
    text = path.read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    matches = sum(1 for line in lines if re.search(r"\bmatch\b", line))
    items = sum(1 for line in lines if ITEM_RE.search(line))
    return FileStats(
        path=path.relative_to(repo),
        lines=len(lines),
        matches=matches,
        items=items,
        extension=path.suffix,
    )


def collect(repo: Path, roots: Iterable[str], globs: Iterable[str]) -> list[FileStats]:
    return sorted(
        (file_stats(repo, path) for path in iter_source_files(repo, roots, globs)),
        key=lambda stat: str(stat.path),
    )


def render_table(headers: tuple[str, ...], rows: Iterable[tuple[object, ...]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(value) for value in row) + " |")
    return lines


def render_markdown(stats: list[FileStats], limit: int) -> str:
    rust_files = [stat for stat in stats if stat.extension == ".rs"]
    python_files = [stat for stat in stats if stat.extension == ".py"]
    total_lines = sum(stat.lines for stat in stats)
    total_matches = sum(stat.matches for stat in stats)
    total_items = sum(stat.items for stat in stats)

    lines: list[str] = [
        "# Code Health Baseline",
        "",
        "Generated by `tools/code_health.py`.",
        "",
        "## Summary",
        "",
        *render_table(
            ("Metric", "Value"),
            (
                ("Source files", len(stats)),
                ("Rust files", len(rust_files)),
                ("Python files", len(python_files)),
                ("Total lines", total_lines),
                ("Rust lines", sum(stat.lines for stat in rust_files)),
                ("Python lines", sum(stat.lines for stat in python_files)),
                ("Rust `match` lines", total_matches),
                ("Rust item lines", total_items),
            ),
        ),
        "",
        "## Longest Rust Files",
        "",
        *render_table(
            ("Lines", "Matches", "Items", "Path"),
            (
                (stat.lines, stat.matches, stat.items, f"`{stat.path}`")
                for stat in sorted(rust_files, key=lambda stat: stat.lines, reverse=True)[:limit]
            ),
        ),
        "",
        "## Longest Python Files",
        "",
        *render_table(
            ("Lines", "Path"),
            (
                (stat.lines, f"`{stat.path}`")
                for stat in sorted(python_files, key=lambda stat: stat.lines, reverse=True)[:limit]
            ),
        ),
        "",
        "## Rust Match Hotspots",
        "",
        *render_table(
            ("Matches", "Lines", "Per 1k Lines", "Path"),
            (
                (stat.matches, stat.lines, f"{stat.match_density:.1f}", f"`{stat.path}`")
                for stat in sorted(rust_files, key=lambda stat: stat.matches, reverse=True)[:limit]
            ),
        ),
        "",
        "## Rust Item Density Hotspots",
        "",
        *render_table(
            ("Items", "Lines", "Path"),
            (
                (stat.items, stat.lines, f"`{stat.path}`")
                for stat in sorted(rust_files, key=lambda stat: stat.items, reverse=True)[:limit]
            ),
        ),
        "",
        "## Oversized Rust Candidates",
        "",
        *render_table(
            ("Lines", "Matches", "Items", "Path"),
            (
                (stat.lines, stat.matches, stat.items, f"`{stat.path}`")
                for stat in sorted(
                    (stat for stat in rust_files if stat.lines >= 2000),
                    key=lambda stat: stat.lines,
                    reverse=True,
                )
            ),
        ),
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path.cwd(), help="repository root")
    parser.add_argument("--limit", type=int, default=25, help="rows per ranked table")
    parser.add_argument("--output", type=Path, help="write the Markdown report to this path")
    parser.add_argument(
        "--root",
        action="append",
        dest="roots",
        help="source root to scan; may be repeated",
    )
    args = parser.parse_args()

    repo = args.repo.resolve()
    roots = args.roots if args.roots else DEFAULT_ROOTS
    stats = collect(repo, roots, DEFAULT_GLOBS)
    report = render_markdown(stats, args.limit)
    if args.output:
        output = args.output
        if not output.is_absolute():
            output = repo / output
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(report + "\n", encoding="utf-8")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
